// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAag7PnQDeXEXg4trZAtel_BM9npOYma0I',
    appId: '1:334913667146:web:4735bca052f69b7b7ea6b3',
    messagingSenderId: '334913667146',
    projectId: 'task-manager-e3067',
    authDomain: 'task-manager-e3067.firebaseapp.com',
    storageBucket: 'task-manager-e3067.firebasestorage.app',
    measurementId: 'G-PL05PYZ31T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGgoyNR7kgeO8JYChWdo4ZWI-IuvAveAY',
    appId: '1:334913667146:android:34808adfa6b3f5867ea6b3',
    messagingSenderId: '334913667146',
    projectId: 'task-manager-e3067',
    storageBucket: 'task-manager-e3067.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCv33TmnMGUjywu-8hjuyuBTisV6aWiRs',
    appId: '1:334913667146:ios:13d73e0369ea43b17ea6b3',
    messagingSenderId: '334913667146',
    projectId: 'task-manager-e3067',
    storageBucket: 'task-manager-e3067.firebasestorage.app',
    iosBundleId: 'com.example.group3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCv33TmnMGUjywu-8hjuyuBTisV6aWiRs',
    appId: '1:334913667146:ios:13d73e0369ea43b17ea6b3',
    messagingSenderId: '334913667146',
    projectId: 'task-manager-e3067',
    storageBucket: 'task-manager-e3067.firebasestorage.app',
    iosBundleId: 'com.example.group3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAag7PnQDeXEXg4trZAtel_BM9npOYma0I',
    appId: '1:334913667146:web:3190a9b0985786f97ea6b3',
    messagingSenderId: '334913667146',
    projectId: 'task-manager-e3067',
    authDomain: 'task-manager-e3067.firebaseapp.com',
    storageBucket: 'task-manager-e3067.firebasestorage.app',
    measurementId: 'G-BZJPWLS7WQ',
  );
}
